# Generated by Django 6.0.4 on 2026-05-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("genre", models.CharField(max_length=100)),
                ("language", models.CharField(max_length=50)),
                ("trailer_url", models.URLField(blank=True)),
            ],
        ),
    ]
