# Generated by Django 6.0.4 on 2026-05-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="poster",
            field=models.ImageField(default=1, upload_to="posters/"),
            preserve_default=False,
        ),
    ]
